label linux
  kernel /boot/zImage
  fdtdir /boot/
  # Debugging options: earlycon=sbi ignore_loglevel and removing quiet
  append console=ttyS4,115200 root=/dev/mmcblk0p3 rootfstype=squashfs rootwait quiet
